### ISSUE TITLE
Error: unknown code: 0xd0

### ISSUE THREAD

**Issue by noffle** [substack/jpeg-marker-stream#2]
read.js:
```js
var jpeg = require('jpeg-marker-stream')
process.stdin.pipe(jpeg())
  .on('data', console.log)
```

Then I ran
```
$ cat foo.jpg | node foo.jpg
```

You can find foo.jpg [here](http://tmp.stephenwhitmore.com/foo.jpg).

This results in [a great deal of output](http://www.stephenwhitmore.com/tmp/jpeg-log.txt), but culminates in the following error:

```
Error: unknown code: 0xd0
    at DestroyableTransform.write [as _transform] (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/jpeg-marker-stream/index.js:80:23)
    at DestroyableTransform.Transform._read (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/home/sww/dev/xform-uploader/tmp/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by mojodna** [comment]
After the work-around in `ddem-observations-server`, it sticks on a different byte (same file):

```
Error: expected 0xff, received: 0xc3
   at DestroyableTransform.write [as _transform] (/Users/seth/src/digidem/ddem-observation-server/node_modules/jpeg-marker-stream/index.js:45:21)
   at DestroyableTransform.Transform._read (/Users/seth/src/digidem/ddem-observation-server/node_modules/readable-stream/lib/_stream_transform.js:159:10)
   at DestroyableTransform.Transform._write (/Users/seth/src/digidem/ddem-observation-server/node_modules/readable-stream/lib/_stream_transform.js:147:83)
   at doWrite (/Users/seth/src/digidem/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:347:64)
   at writeOrBuffer (/Users/seth/src/digidem/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:336:5)
   at DestroyableTransform.Writable.write (/Users/seth/src/digidem/ddem-observation-server/node_modules/readable-stream/lib/_stream_writable.js:274:11)
   at IncomingMessage.ondata (_stream_readable.js:555:20)
   at emitOne (events.js:101:20)
   at IncomingMessage.emit (events.js:188:7)
   at IncomingMessage.Readable.read (_stream_readable.js:381:10)
```

**Comment by michael-ts** [comment]
@mojodna  What workaround, using on.error()?  I'm getting a similar error, "unknown code: 0xc2".

**Comment by mojodna** [comment]
I think https://github.com/mojodna/ddem-observation-server/commit/49c1b62568d18b057ecd533c30b1770ad9485ee5#diff-168726dbe96b3ce427e7fedce31bb0bcR69 is the relevant commit.

Otherwise, I can't remember much, sorry!
